#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/rustdesk/rustdesk /usr/bin/rustdesk
	
	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/camellia.service ]; then
			rm /etc/systemd/system/camellia.service /usr/lib/systemd/system/camellia.service /usr/lib/systemd/user/camellia.service >/dev/null  2>&1
		fi
		version=$(python3 -V 2>&1 | grep -Po '(?<=Python )(.+)')
		parsedVersion=$(echo "${version//./}")
        mkdir -p /usr/lib/systemd/system/
		cp /usr/share/rustdesk/files/systemd/rustdesk.service /usr/lib/systemd/system/camellia.service
		# try fix error in Ubuntu 18.04
		# Failed to reload camellia.service: Unit camellia.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/camellia.service:10: Executable path is not absolute: pkill -f "rustdesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/camellia.service
		fi
		systemctl daemon-reload
		systemctl enable camellia
		systemctl start camellia
	fi
fi
